type Book {
  id: Int!
  title: String!
  author: String!
  # * ฟิลด์อื่นๆ ถ้ามี
}

type Query {
  books: [Book!]!
  book(id: Int!): Book
}

type Mutation {
  addBook(title: String!, author: String!): Book
  deleteBook(id: Int!): Book
  updateBook(id: Int!, title: String, author: String): Book
}